### ISSUE TITLE
Impossible to install via Galaxy

### ISSUE THREAD

**Issue by anthony-robin** [ElaoInfra/ansible-role-backup-manager#1]
As you don't have master branch on your repository, ansible cannot fetch your code:

```
downloading role from https://github.com/ElaoInfra/ansible-role-backup-manager/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
```

**Comment by nervo** [comment]
You can now have a look on our new organization, where every roles have a master branch :) https://github.com/manala
